import { GoalPlan, ProductivityStats, UserPersona, GmailSignal, LocationCommuteSignal, BehaviorLogEntry } from '../types';

export const INITIAL_GOAL_PLAN: GoalPlan = {
  id: 'goal-cse-project-7d',
  title: 'Complete CSE Project in 7 Days',
  persona: 'student',
  targetDays: 7,
  dailyHours: 4,
  energyPeak: 'morning',
  createdAt: new Date().toISOString(),
  status: 'active',
  aiStrategy:
    'Front-loaded architectural sprint with dedicated validation buffers. High-complexity modules scheduled during morning peak energy windows; testing and documentation reserved for afternoons.',
  milestones: [
    {
      id: 'm-1',
      day: 2,
      title: 'Phase 1: Architecture & Data Schema Approved',
      description: 'System architecture diagram, API contract, and database models defined and verified.',
      completed: true,
    },
    {
      id: 'm-2',
      day: 4,
      title: 'Phase 2: Core Business Logic & Endpoints Functional',
      description: 'Main algorithmic engine and REST endpoints passing initial integration test suite.',
      completed: false,
    },
    {
      id: 'm-3',
      day: 6,
      title: 'Phase 3: Frontend Integration & End-to-End Flow',
      description: 'Interactive UI synced with backend API; error boundaries and responsive layout in place.',
      completed: false,
    },
    {
      id: 'm-4',
      day: 7,
      title: 'Phase 4: Final QA, Benchmark & Demo Presentation',
      description: 'Execution of stress tests, slide deck prep, and code repository polished for submission.',
      completed: false,
    },
  ],
  tasks: [
    // Day 1
    {
      id: 'task-1-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 1,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'Requirements Scope & Tech Stack Verification',
      description: 'Lock down functional specs, setup monorepo boilerplate, install dependencies, and setup Git workflow.',
      category: 'Setup & Design',
      estimatedMinutes: 90,
      priority: 'high',
      status: 'completed',
      subtasks: [
        { id: 'st-1', title: 'Review professor rubric & constraints', completed: true },
        { id: 'st-2', title: 'Initialize Git repo with README and .gitignore', completed: true },
        { id: 'st-3', title: 'Install core frameworks and linters', completed: true },
      ],
      focusTips: ['Keep scope strictly aligned with the core grading criteria.'],
    },
    {
      id: 'task-1-2',
      goalId: 'goal-cse-project-7d',
      dayNumber: 1,
      scheduledTime: '11:00 AM',
      timeOfDay: 'morning',
      title: 'Database Schema & Entity Relationship Design',
      description: 'Draft relational tables, foreign key constraints, indexes, and write migration scripts.',
      category: 'Backend',
      estimatedMinutes: 90,
      priority: 'high',
      status: 'completed',
      subtasks: [
        { id: 'st-4', title: 'Draft ER diagram for 5 core entities', completed: true },
        { id: 'st-5', title: 'Define SQL DDL schema definitions', completed: true },
      ],
      focusTips: ['Validate normalization (3NF) to avoid rewrite costs on Day 4.'],
    },
    // Day 2
    {
      id: 'task-2-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 2,
      scheduledTime: '09:30 AM',
      timeOfDay: 'morning',
      title: 'Core Algorithm Implementation & Unit Test Setup',
      description: 'Write the primary computing engine and algorithmic logic for data processing.',
      category: 'Core Logic',
      estimatedMinutes: 120,
      priority: 'high',
      status: 'completed',
      subtasks: [
        { id: 'st-6', title: 'Implement sorting & search optimizations', completed: true },
        { id: 'st-7', title: 'Write 4 unit test assertions for edge cases', completed: true },
      ],
    },
    {
      id: 'task-2-2',
      goalId: 'goal-cse-project-7d',
      dayNumber: 2,
      scheduledTime: '02:00 PM',
      timeOfDay: 'afternoon',
      title: 'API Gateway & Route Handlers',
      description: 'Expose endpoints for authentication, resource query, and update operations.',
      category: 'Backend',
      estimatedMinutes: 90,
      priority: 'medium',
      status: 'completed',
      subtasks: [
        { id: 'st-8', title: 'Build CRUD route controllers', completed: true },
        { id: 'st-9', title: 'Test endpoints with Postman/curl', completed: true },
      ],
    },
    // Day 3 (Current / Active Day)
    {
      id: 'task-3-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 3,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'State Management & API Client Hooks',
      description: 'Configure client-side data fetching, cache invalidation, and custom hooks for frontend communication.',
      category: 'Frontend',
      estimatedMinutes: 100,
      priority: 'high',
      status: 'in_progress',
      subtasks: [
        { id: 'st-10', title: 'Set up Axios/Fetch client wrapper', completed: true },
        { id: 'st-11', title: 'Build React hook for live data queries', completed: false },
        { id: 'st-12', title: 'Implement error toast handling', completed: false },
      ],
      focusTips: ['Turn off social notifications during the first 45-minute sprint block.'],
    },
    {
      id: 'task-3-2',
      goalId: 'goal-cse-project-7d',
      dayNumber: 3,
      scheduledTime: '02:00 PM',
      timeOfDay: 'afternoon',
      title: 'Component Design: Dashboard & Interactive Controls',
      description: 'Implement main views, data tables, and modal forms with Tailwind CSS.',
      category: 'Frontend',
      estimatedMinutes: 110,
      priority: 'medium',
      status: 'pending',
      subtasks: [
        { id: 'st-13', title: 'Construct summary metric cards', completed: false },
        { id: 'st-14', title: 'Add search filter input and pagination', completed: false },
      ],
    },
    // Day 4
    {
      id: 'task-4-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 4,
      scheduledTime: '09:30 AM',
      timeOfDay: 'morning',
      title: 'Integration Testing & Edge Case Hardening',
      description: 'Test network disconnection, bad input payloads, race conditions, and error recovery.',
      category: 'Quality Assurance',
      estimatedMinutes: 100,
      priority: 'high',
      status: 'pending',
      subtasks: [
        { id: 'st-15', title: 'Verify empty state fallbacks', completed: false },
        { id: 'st-16', title: 'Test form validation and boundary checks', completed: false },
      ],
    },
    {
      id: 'task-4-2',
      goalId: 'goal-cse-project-7d',
      dayNumber: 4,
      scheduledTime: '03:00 PM',
      timeOfDay: 'afternoon',
      title: 'Performance Benchmark & Query Indexing',
      description: 'Analyze response times, eliminate N+1 queries, and verify under 200ms latency.',
      category: 'Performance',
      estimatedMinutes: 80,
      priority: 'low',
      status: 'pending',
      subtasks: [
        { id: 'st-17', title: 'Run database EXPLAIN ANALYZE', completed: false },
      ],
    },
    // Day 5
    {
      id: 'task-5-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 5,
      scheduledTime: '10:00 AM',
      timeOfDay: 'morning',
      title: 'User Interface Polish & Responsive Accessibility',
      description: 'Audit color contrast, keyboard navigation, loading skeletons, and mobile viewports.',
      category: 'UI/UX',
      estimatedMinutes: 90,
      priority: 'medium',
      status: 'pending',
      subtasks: [
        { id: 'st-18', title: 'Check responsive breakpoints across mobile and desktop', completed: false },
        { id: 'st-19', title: 'Add keyboard focus rings and ARIA tags', completed: false },
      ],
    },
    // Day 6
    {
      id: 'task-6-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 6,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'Documentation, Architecture Diagrams & README',
      description: 'Write comprehensive installation instructions, architecture breakdown, and screenshots.',
      category: 'Documentation',
      estimatedMinutes: 90,
      priority: 'high',
      status: 'pending',
      subtasks: [
        { id: 'st-20', title: 'Export clean Mermaid diagrams', completed: false },
        { id: 'st-21', title: 'Document environment variables and setup steps', completed: false },
      ],
    },
    // Day 7
    {
      id: 'task-7-1',
      goalId: 'goal-cse-project-7d',
      dayNumber: 7,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'Dry Run Demo & Slide Deck Presentation',
      description: 'Record 3-minute walk-through demo video, review presentation slides, and perform final Git commit.',
      category: 'Presentation',
      estimatedMinutes: 120,
      priority: 'high',
      status: 'pending',
      subtasks: [
        { id: 'st-22', title: 'Prepare 5-slide PowerPoint deck', completed: false },
        { id: 'st-23', title: 'Rehearse live demo questions and answers', completed: false },
        { id: 'st-24', title: 'Tag v1.0.0 release in GitHub', completed: false },
      ],
    },
  ],
  adaptationHistory: [
    {
      id: 'adapt-init',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      reason: 'Initial Schedule Generation',
      affectedTaskIds: ['task-1-1', 'task-1-2'],
      explanation: 'AI allocated morning slots for core architectural modules based on your stated peak energy.',
      changesSummary: 'Generated 7-day adaptive roadmap with 11 balanced sprint items.',
    },
  ],
};

export const QUICK_GOAL_TEMPLATES = [
  {
    title: 'Complete my CSE project in 7 days',
    persona: 'student' as UserPersona,
    days: 7,
    hours: 4,
    energy: 'morning' as const,
    category: 'Academics & Coding',
    desc: 'From requirements & schema design to API logic, frontend, testing, and presentation.',
  },
  {
    title: 'Semester Finals Exam & Assignment Sprint',
    persona: 'student' as UserPersona,
    days: 10,
    hours: 5,
    energy: 'morning' as const,
    category: 'University Exams',
    desc: 'Distributed revision cycle across 4 subjects, past-paper practice, and assignment submission.',
  },
  {
    title: 'Q3 Enterprise Product Feature & Release Sprint',
    persona: 'employee' as UserPersona,
    days: 7,
    hours: 5,
    energy: 'morning' as const,
    category: 'Product & Tech',
    desc: 'Coordinate sprint deliverables, cross-functional client demos, staging QA, and release documentation.',
  },
  {
    title: 'Client Proposal Deck & Market Strategy',
    persona: 'employee' as UserPersona,
    days: 5,
    hours: 4.5,
    energy: 'afternoon' as const,
    category: 'Strategy & Sales',
    desc: 'Market research synthesis, financial modeling, slide deck formatting, and executive rehearsal.',
  },
];

export const PERSONA_CONFIGS: Record<UserPersona, {
  name: string;
  roleTag: string;
  description: string;
  keyNeeds: string[];
  howSynqAIHelps: string[];
  typicalLocations: string[];
  dailyRhythm: string;
  sampleEmailSources: string[];
}> = {
  student: {
    name: 'Student & Academic',
    roleTag: 'University / High School / Researchers',
    description:
      'Students juggle complex assignment rubrics, exam dates, lecture times, campus commutes, and team projects. They need the freedom to record their own study timetable, edit it when classes shift, and auto-balance study sprints when procrastinating.',
    keyNeeds: [
      'Record custom lecture schedules and homework deadlines',
      'Edit and rebalance study sessions around extracurriculars',
      'Google Maps tracking between Dorm, Campus Hall, and Library',
      'Gmail alerts for professor announcements and submission deadlines',
    ],
    howSynqAIHelps: [
      'Breaks down massive projects (e.g., 7-day CSE project) into digestible daily study blocks.',
      'Calculates walk/transit time to campus so you arrive at lectures punctually.',
      'Scans assignment emails to extract due dates and insert auto-reminders.',
      'Provides guilt-free rescheduling when exam cramming causes fatigue.',
    ],
    typicalLocations: ['Dorm / Home', 'Campus Engineering Lab', 'Central University Library', 'Study Café'],
    dailyRhythm: 'Classes in morning/early afternoon, deep study blocks in late afternoon and evening.',
    sampleEmailSources: ['Canvas / Blackboard LMS', 'Professor Office Hours', 'Project Team Discord/Gmail', 'Academic Portal'],
  },
  employee: {
    name: 'Employee & Professional',
    roleTag: 'Software Engineers / Managers / Remote Workers',
    description:
      'Working professionals must protect deep focus blocks amidst scattered meetings, client requests, Jira tickets, and daily office commutes. They record their work sprints, freely edit their tasks as priorities change, and rely on real-time traffic and email updates.',
    keyNeeds: [
      'Record and adjust work sprints, client deliverables, and standup prep',
      'Freely edit task priorities when urgent boss/client requests arrive',
      'Google Maps live commute tracking with traffic leave-by alarms',
      'Gmail monitoring for urgent manager emails, client change orders, and meeting invites',
    ],
    howSynqAIHelps: [
      'Carves protected 90-minute focus windows around fragmented meeting schedules.',
      'Alerts you when highway traffic surges so you leave on time for office meetings.',
      'Detects urgent email threads to dynamically suggest task priority adjustments.',
      'Reorganizes unfinished work when production bugs or emergency meetings disrupt your day.',
    ],
    typicalLocations: ['Home Office', 'Headquarters / Corporate Office', 'Client Site', 'Coworking Hub'],
    dailyRhythm: 'Morning standup & high-focus work, afternoon client syncs and collaborative reviews.',
    sampleEmailSources: ['Google Workspace / Gmail', 'Jira / GitHub notifications', 'Manager / Executive Directives', 'Client Contracts'],
  },
};

export const INITIAL_EMPLOYEE_GOAL_PLAN: GoalPlan = {
  id: 'goal-enterprise-sprint',
  title: 'Q3 Enterprise Product Feature & Release Sprint',
  persona: 'employee',
  targetDays: 7,
  dailyHours: 5,
  energyPeak: 'morning',
  createdAt: new Date().toISOString(),
  status: 'active',
  aiStrategy:
    'Enterprise focus sprint: High-cognitive coding and system architecture locked into morning peak hours before standups and client review meetings. Buffer zones reserved for code reviews and QA in the afternoon.',
  milestones: [
    {
      id: 'em-1',
      day: 2,
      title: 'Milestone 1: Technical Spec & Architecture Signoff',
      description: 'API schemas, data contracts, and security review completed with Engineering Lead.',
      completed: true,
    },
    {
      id: 'em-2',
      day: 4,
      title: 'Milestone 2: Core Feature Implementation & PRs Ready',
      description: 'Business logic implemented, unit test coverage >85%, and draft PR opened for review.',
      completed: false,
    },
    {
      id: 'em-3',
      day: 6,
      title: 'Milestone 3: Staging Deployment & UAT Verification',
      description: 'Deployed to staging environment; cross-browser QA and stakeholder walkthrough finished.',
      completed: false,
    },
    {
      id: 'em-4',
      day: 7,
      title: 'Milestone 4: Production Release & Team Retrospective',
      description: 'Canary release deployed, telemetry dashboards monitored, and release notes published.',
      completed: false,
    },
  ],
  tasks: [
    {
      id: 'emp-1-1',
      goalId: 'goal-enterprise-sprint',
      dayNumber: 1,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'Technical Spec Drafting & Security Threat Modeling',
      description: 'Document endpoints, payload schemas, and ensure compliance with enterprise SOC2 standards.',
      category: 'Architecture',
      estimatedMinutes: 90,
      priority: 'high',
      status: 'completed',
      locationRequired: 'Office Desk 4B',
      personaTag: 'employee',
      subtasks: [
        { id: 'est-1', title: 'Write OpenAPI schema spec', completed: true },
        { id: 'est-2', title: 'Review with security architect', completed: true },
      ],
    },
    {
      id: 'emp-1-2',
      goalId: 'goal-enterprise-sprint',
      dayNumber: 1,
      scheduledTime: '02:00 PM',
      timeOfDay: 'afternoon',
      title: 'Cross-functional Team Standup & Backlog Grooming',
      description: 'Align sprint points with frontend and QA leads; map out dependencies.',
      category: 'Coordination',
      estimatedMinutes: 60,
      priority: 'medium',
      status: 'completed',
      locationRequired: 'Conference Room Alpha',
      personaTag: 'employee',
      subtasks: [
        { id: 'est-3', title: 'Update Jira story point estimates', completed: true },
      ],
    },
    {
      id: 'emp-2-1',
      goalId: 'goal-enterprise-sprint',
      dayNumber: 2,
      scheduledTime: '09:30 AM',
      timeOfDay: 'morning',
      title: 'Core Service Microservice Endpoint Implementation',
      description: 'Build backend business logic, database transactions, and error middleware.',
      category: 'Backend Dev',
      estimatedMinutes: 120,
      priority: 'high',
      status: 'completed',
      locationRequired: 'Headquarters / Desk 4B',
      personaTag: 'employee',
      subtasks: [
        { id: 'est-4', title: 'Implement transactional repository queries', completed: true },
        { id: 'est-5', title: 'Add unit tests for concurrency edge cases', completed: true },
      ],
    },
    {
      id: 'emp-3-1',
      goalId: 'goal-enterprise-sprint',
      dayNumber: 3,
      scheduledTime: '09:00 AM',
      timeOfDay: 'morning',
      title: 'API Gateway Integration & Client SDK Generation',
      description: 'Connect internal microservice routes to the public proxy with rate limiting.',
      category: 'DevOps & API',
      estimatedMinutes: 100,
      priority: 'high',
      status: 'in_progress',
      locationRequired: 'Office Desk 4B',
      personaTag: 'employee',
      subtasks: [
        { id: 'est-6', title: 'Configure reverse proxy routes', completed: true },
        { id: 'est-7', title: 'Test token authentication verification', completed: false },
      ],
    },
    {
      id: 'emp-3-2',
      goalId: 'goal-enterprise-sprint',
      dayNumber: 3,
      scheduledTime: '02:30 PM',
      timeOfDay: 'afternoon',
      title: 'Prepare Staging Demo for Stakeholder Review',
      description: 'Prepare 5-min walk-through and endpoint status verified for client review call.',
      category: 'Client Sync',
      estimatedMinutes: 60,
      priority: 'high',
      status: 'pending',
      locationRequired: 'Client Meeting Room 2',
      personaTag: 'employee',
      subtasks: [
        { id: 'est-8', title: 'Verify staging health check', completed: false },
        { id: 'est-9', title: 'Prepare slide agenda', completed: false },
      ],
    },
  ],
  adaptationHistory: [
    {
      id: 'emp-adapt-1',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      reason: 'Employee Persona Setup',
      affectedTaskIds: ['emp-1-1', 'emp-1-2'],
      explanation: 'Scheduled focused morning development sessions to insulate against afternoon meeting fragmentation.',
      changesSummary: 'Protected 3.5 hours of morning deep work per corporate schedule.',
    },
  ],
};

export const SAMPLE_GMAIL_SIGNALS: GmailSignal[] = [
  {
    id: 'gm-1',
    from: 'prof.smith@university.edu',
    subject: 'URGENT: CSE 401 Project Prototype Submission Date Updated',
    snippet: 'Dear class, please ensure your architectural schemas and Git repositories are submitted by Friday at 11:59 PM sharp...',
    date: 'Today, 08:15 AM',
    detectedDeadline: 'Friday, 11:59 PM',
    suggestedTaskTitle: 'Submit CSE 401 Project Prototype to Canvas Portal',
    priority: 'urgent',
    type: 'assignment',
    appliedToSchedule: true,
  },
  {
    id: 'gm-2',
    from: 'manager.clara@enterprise.com',
    subject: 'Client Sync: Staging Demo Moved to 02:30 PM',
    snippet: 'Hi team, the client requested we push the staging review up by 1 hour. Please prepare your slide demo and endpoint status...',
    date: 'Today, 09:40 AM',
    detectedDeadline: 'Today, 02:30 PM',
    suggestedTaskTitle: 'Prepare 5-min Staging Demo for Client Call',
    priority: 'urgent',
    type: 'meeting',
    appliedToSchedule: false,
  },
  {
    id: 'gm-3',
    from: 'academics-notice@university.edu',
    subject: 'Library Extended Hours for Final Exam Week',
    snippet: 'The main campus library will remain open 24 hours starting this Monday with silent study pods available...',
    date: 'Yesterday, 04:20 PM',
    priority: 'info',
    type: 'announcement',
    appliedToSchedule: false,
  },
];

export const SAMPLE_LOCATION_COMMUTE: LocationCommuteSignal = {
  currentLocation: 'Home / Residence (North District)',
  destination: 'Corporate HQ / University Campus (Tech Park)',
  commuteMinutes: 32,
  distanceKm: 14.8,
  traffic: 'moderate',
  leaveByTime: '08:18 AM',
  targetArrivalTime: '08:55 AM',
  recommendation: 'Current traffic on Main Ave is moderate (+6 mins delay). Leave by 08:18 AM to ensure a calm arrival for your 09:00 AM session.',
};

export const SAMPLE_BEHAVIOR_LOGS: BehaviorLogEntry[] = [
  {
    id: 'bl-1',
    timestamp: '08:15 AM',
    source: 'gmail',
    title: 'Gmail Signal Detected: Professor Project Notice',
    description: 'Received email from Prof. Smith regarding CSE 401 milestone rubric.',
    impact: 'Added deadline reminder to Day 4 schedule.',
  },
  {
    id: 'bl-2',
    timestamp: '08:30 AM',
    source: 'google_maps',
    title: 'Google Maps Commute Calculation',
    description: 'Recorded 32-min transit time from Home to Campus Lab via Tech Blvd.',
    impact: 'Scheduled proactive "Leave by 08:18 AM" audio & banner reminder.',
  },
  {
    id: 'bl-3',
    timestamp: '09:05 AM',
    source: 'location_sensor',
    title: 'Arrived at Focus Location: Campus Engineering Hub',
    description: 'GPS confirmed arrival at target workspace.',
    impact: 'Triggered deep focus room notification with ambient sound preset.',
  },
];
